### PR TITLE
Fix cf integration tests

### PR DESCRIPTION
**Pull request by rshewitt**
# Pull Request

Related to [4706](https://github.com/GSA/data.gov/issues/4706)

## PR TASKS

- [x] The actual code changes.
- [x] Tests written and passed.
- [x] Any changes to docs?
- [x] Bumped version number in [pyproject.toml](https://github.com/GSA/datagov-harvesting-logic/blob/8078c5b9f015ca7fb8a142e4e4b2e22ad2fd49b1/pyproject.toml#L3) (also checked on [PyPi](https://pypi.org/project/ckanext-geodatagov/#history)).

### CODE REVIEW

**Comment by rshewitt** [comment]
Screenshot 2024-04-23 at 7 21 58 AM

**Comment by rshewitt** [comment]
I ended up consolidating some of the tests into a single integration test because I need the `guid` of the task assigned by cf to get the task, delete the task, or read logs from the task. I originally passed the task name which I controlled in my fixture but that was proving unreliable.

**Comment by rshewitt** [comment]
I also ended up removing the example cf credential vars from the .env file to avoid having env vars be in more than 1 place ( secret vs .env ).  i updated the readme with local integration testing info.

**Review by btylerburton — APPROVED** [review]
Nice fixes

**Pull request merged**
