### PR TITLE
refactor download_json into utils.json_utils

### PR DESCRIPTION
**Pull request by robert-bryson**
# Pull Request

Refactoring utils into a unified place. 

## About

Based on discussion in sync today, PR to refactor/tidy up naming for ease of use and readability. 

## PR TASKS

- [ ] The actual code changes.
- [ ] Tests written and passed.
- [ ] Any changes to docs?
- [ ] Bumped version number in [pyproject.toml](https://github.com/GSA/datagov-harvesting-logic/blob/8078c5b9f015ca7fb8a142e4e4b2e22ad2fd49b1/pyproject.toml#L3) (also checked on [PyPi](https://pypi.org/project/ckanext-geodatagov/#history)).

### CODE REVIEW

**Comment by robert-bryson** [comment]
@rshewitt , this is something like what I was thinking. I like that imports can now be:

 ```python
from harvester.extract.dcatus import parse_catalog
from harvester.utils.s3 import upload_to_S3
from harvester.utils.json import download_json
from harvester.validate.dcat_us import is_dcatus_schema
```
rather than:
```python
from datagovharvester.extract.dcatus import parse_catalog
from datagovharvester.extract.utils import download_json
from datagovharvester.utils.s3_utilities import upload_to_S3
from datagovharvester.validate.dcat_us import is_dcatus_schema
```

How does that look to you? Anyone else on @GSA/data-gov-team have thoughts?

**Comment by btylerburton** [comment]
LGTM @robert-bryson. Also, FYI, I got the notification when mentioning the team.

**Review by btylerburton — APPROVED** [review]
🚢

**Review by jbrown-xentity — APPROVED** [review]
Forgot this needs 2 people's approval... Nice cleanup iteration!

**Pull request merged**
