### PR TITLE
Airflow etl test reid

### PR DESCRIPTION
**Pull request by rshewitt**
# Pull Request

Related to [4422](https://github.com/GSA/data.gov/issues/4422)

## About

getting airflow running locally 

## PR TASKS

- [ ] The actual code changes.
- [ ] Tests written and passed.
- [ ] Any changes to docs?
- [ ] Bumped version number in [pyproject.toml](https://github.com/GSA/datagov-harvesting-logic/blob/8078c5b9f015ca7fb8a142e4e4b2e22ad2fd49b1/pyproject.toml#L3) (also checked on [PyPi](https://pypi.org/project/ckanext-geodatagov/#history)).

### CODE REVIEW

**Review by btylerburton — CHANGES_REQUESTED** [review]
can you update the naming conventions of the files to reflect their format & schema? 

like, DAGS are for DCAT only, and json schemas are for DATAJSON / DCAT.

**Comment by rshewitt** [comment]
> can you update the naming conventions of the files to reflect their format & schema?
> 
> like, DAGS are for DCAT only, and json schemas are for DATAJSON / DCAT.

renamed and reorganized

**Review by rshewitt — COMMENTED** [review]
updated name of dag and schemas to dcatus

**Review by rshewitt — COMMENTED** [review]
updated.

**Review by nickumia-reisys — DISMISSED** [review]
🧮

**Review by btylerburton — DISMISSED** [review]

**Review by robert-bryson — APPROVED** [review]

**Pull request merged**
